# Workflow de integración continua para proyecto factorial
# Ejecuta linting con pylint y tests con pytest

name: CI para proyecto factorial

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Ejecutar CI
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4
    
    - name: Configurar Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Analizar código con pylint (mínimo 10)
      run: |
        pylint src --fail-under=10
        
    - name: Ejecutar pruebas con pytest
      run: |
        python -m pytest --cov=src tests/
